### PR TITLE
Adds FNF logo and buttons to connect to servers in main menu

### PR DESCRIPTION
**Pull request by ilbinek**
Adds FNF logo to splash screens, main menu and adds buttons, that will start the connect process to early/late segment servers.

After clicking the EARLY/LATE buttons, it will ask for a password.
Would suggest someone with an artistic feel remakes the connect buttons, it's simple text on a background.

How it looks when this part of the addon is enabled:
image

### CODE REVIEW

**Comment by Mallen-git** [comment]
I like the idea of this a lot but considering we change the password every event now it wouldn't be ideal as the connection would always fail,
When I get back from holiday can always look at adding a pop-up for a password that defaults to our default.
Will also get the high Res fnf logo on there as well

**Comment by ilbinek** [comment]
> I like the idea of this a lot but considering we change the password every event now it wouldn't be ideal as the connection would always fail, When I get back from holiday can always look at adding a pop-up for a password that defaults to our default. Will also get the high Res fnf logo on there as well

That's the beauty of it. With no password provided, it will open the default password promt you would get anyway. That was one of the things I tested and made sure worked.

FNF logo should be high res enough. It's just pixelated because of the screenshot was taken on 1080p Res on 1444p monitor. Looks ok in game.

What I was thinking was making the space between the connect buttons wider a little. But I would leave that to someone with artistic feel.

**Comment by Mallen-git** [comment]
Oh that's perfect then, I'd still want to up the Res purely because we do have proper assets for that that I can pinch and would just mean arma has to deal with the scaling, but yeah I'll do a test when I get home then merge and maybe make the buttons look a little prettier or something, thanks for the work though!

**Comment by Mallen-git** [comment]
Just letting you know tried it out in prod and it doesnt work like you described, instead just showing a connecting failed making the buttons usless, so some kind of pop-up with a password would have to be implemented to make it work

**Comment by ilbinek** [comment]
Was the server online when testing?

If the connection fails, it won't show the password field.

**Comment by ilbinek** [comment]
Using domain names is not supported by connectToServer, changed for direct IPs.
Now works as described, opening the default password prompt.

**Pull request merged**
